"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EthereumUtils__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EthereumUtils__factory_1 = require("./EthereumUtils__factory");
Object.defineProperty(exports, "EthereumUtils__factory", { enumerable: true, get: function () { return EthereumUtils__factory_1.EthereumUtils__factory; } });
//# sourceMappingURL=index.js.map