"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhitelistVotersACLv1__factory = exports.GaslessVoting__factory = exports.DAOv1__factory = exports.AllowVotersACLv1__factory = exports.AllowAllACLv1__factory = exports.typesSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.typesSol = __importStar(require("./Types.sol"));
var AllowAllACLv1__factory_1 = require("./AllowAllACLv1__factory");
Object.defineProperty(exports, "AllowAllACLv1__factory", { enumerable: true, get: function () { return AllowAllACLv1__factory_1.AllowAllACLv1__factory; } });
var AllowVotersACLv1__factory_1 = require("./AllowVotersACLv1__factory");
Object.defineProperty(exports, "AllowVotersACLv1__factory", { enumerable: true, get: function () { return AllowVotersACLv1__factory_1.AllowVotersACLv1__factory; } });
var DAOv1__factory_1 = require("./DAOv1__factory");
Object.defineProperty(exports, "DAOv1__factory", { enumerable: true, get: function () { return DAOv1__factory_1.DAOv1__factory; } });
var GaslessVoting__factory_1 = require("./GaslessVoting__factory");
Object.defineProperty(exports, "GaslessVoting__factory", { enumerable: true, get: function () { return GaslessVoting__factory_1.GaslessVoting__factory; } });
var WhitelistVotersACLv1__factory_1 = require("./WhitelistVotersACLv1__factory");
Object.defineProperty(exports, "WhitelistVotersACLv1__factory", { enumerable: true, get: function () { return WhitelistVotersACLv1__factory_1.WhitelistVotersACLv1__factory; } });
//# sourceMappingURL=index.js.map