/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "string",
                        name: "ipfsHash",
                        type: "string",
                    },
                    {
                        internalType: "uint16",
                        name: "numChoices",
                        type: "uint16",
                    },
                    {
                        internalType: "bool",
                        name: "publishVotes",
                        type: "bool",
                    },
                ],
                internalType: "struct ProposalParams",
                name: "_params",
                type: "tuple",
            },
        ],
        name: "createProposal",
        outputs: [
            {
                internalType: "ProposalId",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "getACL",
        outputs: [
            {
                internalType: "contract PollACLv1",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "voter",
                type: "address",
            },
            {
                internalType: "ProposalId",
                name: "proposalId",
                type: "bytes32",
            },
            {
                internalType: "uint256",
                name: "choiceIdBig",
                type: "uint256",
            },
        ],
        name: "proxyVote",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export class AcceptsProxyVotes__factory {
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
AcceptsProxyVotes__factory.abi = _abi;
//# sourceMappingURL=AcceptsProxyVotes__factory.js.map