/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AcceptsProxyVotes__factory } from "./AcceptsProxyVotes__factory";
export { PollACLv1__factory } from "./PollACLv1__factory";
//# sourceMappingURL=index.js.map