/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EthereumUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthereumUtils__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AllowAllACLv1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowAllACLv1__factory>;
    getContractFactory(
      name: "AllowVotersACLv1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowVotersACLv1__factory>;
    getContractFactory(
      name: "DAOv1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DAOv1__factory>;
    getContractFactory(
      name: "GaslessVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GaslessVoting__factory>;
    getContractFactory(
      name: "AcceptsProxyVotes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AcceptsProxyVotes__factory>;
    getContractFactory(
      name: "PollACLv1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PollACLv1__factory>;
    getContractFactory(
      name: "WhitelistVotersACLv1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitelistVotersACLv1__factory>;

    getContractAt(
      name: "EthereumUtils",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EthereumUtils>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AllowAllACLv1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AllowAllACLv1>;
    getContractAt(
      name: "AllowVotersACLv1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AllowVotersACLv1>;
    getContractAt(
      name: "DAOv1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DAOv1>;
    getContractAt(
      name: "GaslessVoting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GaslessVoting>;
    getContractAt(
      name: "AcceptsProxyVotes",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AcceptsProxyVotes>;
    getContractAt(
      name: "PollACLv1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PollACLv1>;
    getContractAt(
      name: "WhitelistVotersACLv1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitelistVotersACLv1>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
