/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  EthereumUtils,
  EthereumUtilsInterface,
} from "../../../../@oasisprotocol/sapphire-contracts/contracts/EthereumUtils";

const _abi = [
  {
    inputs: [],
    name: "DER_Split_Error",
    type: "error",
  },
  {
    inputs: [],
    name: "expmod_Error",
    type: "error",
  },
  {
    inputs: [],
    name: "k256Decompress_Invalid_Length_Error",
    type: "error",
  },
  {
    inputs: [],
    name: "k256DeriveY_Invalid_Prefix_Error",
    type: "error",
  },
  {
    inputs: [],
    name: "recoverV_Error",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212204a0608d7bdc5040ddffbd702a496a3bf8f5e654fc0085ddabbb9b57c3936f2fb64736f6c63430008100033";

type EthereumUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumUtils__factory extends ContractFactory {
  constructor(...args: EthereumUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EthereumUtils> {
    return super.deploy(overrides || {}) as Promise<EthereumUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EthereumUtils {
    return super.attach(address) as EthereumUtils;
  }
  override connect(signer: Signer): EthereumUtils__factory {
    return super.connect(signer) as EthereumUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumUtilsInterface {
    return new utils.Interface(_abi) as EthereumUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthereumUtils {
    return new Contract(address, _abi, signerOrProvider) as EthereumUtils;
  }
}
