"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PollACLv1__factory = exports.AcceptsProxyVotes__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AcceptsProxyVotes__factory_1 = require("./AcceptsProxyVotes__factory");
Object.defineProperty(exports, "AcceptsProxyVotes__factory", { enumerable: true, get: function () { return AcceptsProxyVotes__factory_1.AcceptsProxyVotes__factory; } });
var PollACLv1__factory_1 = require("./PollACLv1__factory");
Object.defineProperty(exports, "PollACLv1__factory", { enumerable: true, get: function () { return PollACLv1__factory_1.PollACLv1__factory; } });
//# sourceMappingURL=index.js.map